### ISSUE TITLE
After Disconnecting the bot with command If we play a song it will send the message started playing but the bot wont join the vc

### ISSUE THREAD

**Issue by DarkLord2431** [naseif/Eyesense-Music-Bot#8]
I don't know why but if I disconnect the bot with -disconnect the bot will disconnect but if we try to play any song it will send Music embed but it wont join the VC

**Comment by naseif** [comment]
I just reproduced the issue and you are right, I will look into it now

**Comment by naseif** [comment]
I for some reason was only destroying the StreamDispatcher connection while I should destroy/end the current queue when using disconnect. Please update the bot and let me know if its working fine now

**Comment by DarkLord2431** [comment]
Hi, I have fixed the disconnect to fix it we have to replace line 54 with "await queue.destroy(true);"
